### PR TITLE
Api34 3.x

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by SM2A** [comment]
Without a doubt you are much more experienced than me
The reason that the test are failing this exactly what I am facing
Maybe it's needed to dived `registerReceiver` method into pre api 34 and post 34 that have `RECEIVER_NOT_EXPORTED` flag

**Comment by hannesa2** [comment]
Now it miss something described here https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

**Comment by SM2A** [comment]
Specifying these two permission in manifest will fix it

```
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.USE_EXACT_ALARM" />
```

**Comment by hannesa2** [comment]
There is already one of them. https://github.com/hannesa2/paho.mqtt.android/blob/api34-3.x/serviceLibrary/src/main/AndroidManifest.xml

Please make a pull request based on my branch, then we see, if all is fine then

**Pull request merged**
