### PR TITLE
Replace deprecated local broadcast with Flow

### PR DESCRIPTION
**Pull request by hannesa2**
@chihung93  
It's a copy of #372 to be able to rebase it and trigger CI with new test environment

### CODE REVIEW

**Comment by chihung93** [comment]
Hi @hannesa2 , Thank you for your effort on that. I think my PR does not match the Testcases. Should I close it? I spent many hours but its not pass the test. Thanks

**Comment by hannesa2** [comment]
> Hi @hannesa2 , Thank you for your effort on that. I think my PR does not match the Testcases. Should I close it? I spent many hours but its not pass the test. Thanks

I'm not sue what to to do exactly. I would love to have your changes, but I don't want to remove the tests

**Comment by hannesa2** [comment]
When I look into test,I see there is a problem with connection to server
image

**Comment by chihung93** [comment]
> When I look into test,I see there is a problem with connection to server image

I have debugged it. the issues are threads.

        private val pool = Executors.newCachedThreadPool()

**Comment by hannesa2** [comment]
> I have debugged it. the issues are threads.
> 
> ```
>     private val pool = Executors.newCachedThreadPool()
> ```

Looks promising local ! How do you figured this out ?

**Comment by chihung93** [comment]
> > I have debugged it. the issues are threads.
> > ```
> >     private val pool = Executors.newCachedThreadPool()
> > ```
> 
> Looks promising local ! How do you figured this out ?

I debug from this method: testMultipleClients

The issues related to MqttTokenAndroid which has a wait and complete method.

I'm using Dispatchers.IO thread, so that is why it is not running incorrectly. But I do not know how to fix it. I'm trying to figure the way to make it work :(((

**Comment by hannesa2** [comment]
I already merged https://github.com/hannesa2/paho.mqtt.android/pull/396 to replace this `Executors.newCachedThreadPool()` but without success

**Comment by chihung93** [comment]
Screenshot 2022-11-19 at 18 08 45
The test cases result from the master branch passed 23/24 cases


I have changed the code again with the same result

Screenshot 2022-11-19 at 18 14 24

**Comment by hannesa2** [comment]
closed with #495

**Pull request closed without merging**
