### PR TITLE
Fix android 14 implicit intent for not exported broadcast receivers

### PR DESCRIPTION
**Pull request by SM2A**

### CODE REVIEW

**Comment by SM2A** [comment]
https://github.com/hannesa2/paho.mqtt.android/pull/551#discussion_r1456315845

**Comment by SM2A** [comment]
Thanks

**Comment by JorisBodin** [comment]
Hello,

It's to fix this?
https://sentry-mobile.infomaniak.com/share/issue/f0e2e7d50c7a409fa03997533f4236fb/

**Comment by hannesa2** [comment]
No clue what you writing about 
image
btw, I will not do it

**Comment by hannesa2** [comment]
I recommend to simply move to recent version. It will give you the answer

**Comment by JorisBodin** [comment]
Sentry is an open-source solution, I share the stacktrace where we have many crashes under 4.0 and 4.1 ...

> I recommend to simply move to recent version. It will give you the answer
And which is the most recent version?

In 3.6.1 we have :
android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{ef328f9 6356:com.infomaniak.drive/u0a192} targetSDK=34 has been prohibited

Which is no better :(

**Pull request merged**
