### PR TITLE
Fix for exact alarms not allowed

### PR DESCRIPTION
**Pull request by wwqbus**
added a check if exact alarms are allowed to be schedeuled other wise put a warning in logs and use normasl schedule 

also removed use exact alarm as this is only allowed for calendar apps

### CODE REVIEW

**Comment by hannesa2** [comment]
Hmm, tests are failing 
image

**Comment by wwqbus** [comment]
> Hmm, tests are failing image

i am gonna check to see what the issue is

**Comment by wwqbus** [comment]
ran the tests they seem to succeseed now

**Comment by hannesa2** [comment]
Thanks a lot !

**Pull request merged**
