### PR TITLE
Remove forground service

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by NinaTietje** [comment]
Hi Hannes,
do you already know when you will include this in a new version?
If it's already working and you just need a few people to test it, let me know. :)

**Comment by hannesa2** [comment]
I was interrupted testing it, and I've no clue when I find time to continue. but you can test/use it as well
`implementation 'com.github.hannesa2:paho.mqtt.android:RemoveForegroundService-4.2.3-ga481f07-13'`

The wain question is: does it need a foreground service when the stuff is working with `Workmanager` ?
`Workmanager` run just for seconds, then it need some special handling to run long running tasks, e.g connect and receive new massages.

**Comment by hannesa2** [comment]
> If it's already working and you just need a few people to test it, let me know. :)

The missing test is: 
Do you receive messages, when device is sleeping. The workmanager should awake device, receive messages and fall alseep again. This means you should send e.g every minute a messages over a period > 10 minutes and observe if a notification appears in status bar when device is in standby

**Comment by NinaTietje** [comment]
Hey Hannes,
here is what I tested: I ran your extendedSample from the RemoveForegroundService branch, unplugged the device, switched to the lock screen and published messages for some minutes. After a few minutes (not reached the 10 minutes) the notifications weren’t displayed anymore. In many cases the connection was lost (Lost connection notification) before the 10 minutes were reached. I also tested it while the app was in background and the screen was active, same results.
But I got the same behaviour for the extendedSample from 4.2.3.

Is there anything I should have done differently?
Tested on a Android 12 device.

**Comment by hannesa2** [comment]
Thanks a lot for your tests !
As there is no difference between the version and both stop working, maybe there is a general issue.
The connection lost should be normal, but it should reconnect and receive messages in `WorkManager` task.

Do you observe a working `WorkManager` task in the background ?

**Comment by NinaTietje** [comment]
I will try to check the WorkManager task in the next days or weeks.

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.3-beta1
Please give me feedback if it works for you, independent if successful or not 1

**Pull request merged**
