### PR TITLE
deprecated(service): remove local broadcast manager

### PR DESCRIPTION
**Pull request by chihung93**
Link: https://developer.android.com/jetpack/androidx/releases/localbroadcastmanager

Please take a look this PR instead of my previous PR here: https://github.com/hannesa2/paho.mqtt.android/pull/391

Thanks

### CODE REVIEW

**Comment by hannesa2** [comment]
@chihung93 Please can you rebase to avoid conflicts

**Comment by hannesa2** [comment]
It's much simply 👍 
Do you understand the issue from usage of Flow ?

**Comment by chihung93** [comment]
Screenshot 2022-11-19 at 18 25 58
Just a min, Im running the testcases

**Comment by chihung93** [comment]
Screenshot 2022-11-19 at 18 28 43

its passed all cases.


@hannesa2 :

`Do you understand the issue from usage of Flow ?`
I guess the primary reason is multiple threads when we call CoroutineScope(Dispatchers.IO) multiple times. I think It should be in a  scope

https://developer.android.com/guide/components/broadcasts
    private val scope = CoroutineScope(SupervisorJob())

**Comment by hannesa2** [comment]
Cool, thank you !

**Pull request merged**
