### PR TITLE
fix: make userContext is nullable (#209)

### PR DESCRIPTION
**Pull request by vuptt**
fix issue #209

### CODE REVIEW

**Comment by hannesa2** [comment]
I know it's annoying, but I don't want to merge a failing pull request.

**Comment by hannesa2** [comment]
Here it's failing https://github.com/hannesa2/paho.mqtt.android/blob/master/extendedSample/src/androidTest/java/info/mqtt/android/extsample/activity/ExtendedPublishTest.kt#L47

**Comment by hannesa2** [comment]
You see it in the name of the failing screenshot `L47`
image

**Comment by hannesa2** [comment]
Any idea ?

**Comment by vuptt** [comment]
@hannesa2 that's weird, it looks ok on my side. I think might be the simulator has problems. Is the application navigated to home screen yet, or it still in Add Connection screen?

**Comment by hannesa2** [comment]
When I compare screenshot with my emulator

image

I see this action title. Please try to remove this line (nobody needs it)

`android:title="@string/action_add_connection"`

https://github.com/hannesa2/paho.mqtt.android/blob/master/extendedSample/src/main/res/menu/menu_edit_connection.xml#L10

**Comment by vuptt** [comment]
I try to use withId instead of withContentDescription. It might be more specific

**Pull request merged**
